/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  Student,
  ActivitySubmission,
  PointRule,
  RankPointRule,
  PointHistoryRecord,
  FeaturedStudentTitle,
  AchievementBadge,
  IssuedCertificate,
  AppNotification,
  AuditLog,
  AppSettings,
} from '../types';

export const INITIAL_SETTINGS: AppSettings = {
  organizationName: 'Darul Huda Islamic University',
  tagline: 'Students Outreach & Academic Achievement Dashboard',
  logoUrl: '',
  address: 'Academic Enclave, University Avenue, Knowledge Park, Metro City',
  phone: '+1 (800) 456-7890',
  email: 'outreach@imperialcollege.edu',
  website: 'https://outreach.imperialcollege.edu',
  description: 'A centralized institutional platform recording, validating, and celebrating student excellence, publications, symposiums, paper presentations, competitions, and honours.',
  theme: 'academic_blue',
  publicLeaderboard: true,
  publicAchievements: true,
  publicPublications: true,
  featuredStudentsSection: true,
  studentNamesPublic: true,
  adminUsername: 'admin',
  adminPasswordHash: 'admin123',
  // Front Page Hero Defaults
  heroBadgeText: 'Celebrating Student Excellence & Institutional Outreach',
  heroHeadingPrefix: 'Students Outreach',
  heroHeadingHighlight: 'Dashboard',
  heroDescription: 'A comprehensive academic platform honouring student achievements, literary publications, research symposiums, collegiate programs, competitions, and merit rankings.',
  heroPrimaryBtnText: 'Explore Achievements',
  heroSecondaryBtnText: 'Student Login',
  heroShowBadge: true,
  heroShowStats: true,
  showAnnouncementBar: false,
  announcementBarText: 'Welcome to the Official Academic Achievement & Outreach Portal 2025-2026',
};

export const INITIAL_POINT_RULES: PointRule[] = [
  // Publications
  { id: 'pr-1', category: 'publication', activityType: 'Article', recommendedPoints: 10, maxPoints: 20, isActive: true, adminNote: 'Standard newspaper or peer magazine article' },
  { id: 'pr-2', category: 'publication', activityType: 'Ghazal', recommendedPoints: 15, maxPoints: 25, isActive: true, adminNote: 'Original poetic ghazal published in recognized journal' },
  { id: 'pr-3', category: 'publication', activityType: 'Naat', recommendedPoints: 20, maxPoints: 30, isActive: true, adminNote: 'Devotional literary composition' },
  { id: 'pr-4', category: 'publication', activityType: 'Essay', recommendedPoints: 12, maxPoints: 20, isActive: true, adminNote: 'Analytical or literary essay' },
  { id: 'pr-5', category: 'publication', activityType: 'Poem', recommendedPoints: 10, maxPoints: 20, isActive: true, adminNote: 'Original poetic verse' },
  { id: 'pr-6', category: 'publication', activityType: 'Story', recommendedPoints: 15, maxPoints: 25, isActive: true, adminNote: 'Short story or narrative fiction' },
  { id: 'pr-7', category: 'publication', activityType: 'Research Article', recommendedPoints: 30, maxPoints: 50, isActive: true, adminNote: 'Peer-reviewed research publication / Scopus' },
  { id: 'pr-8', category: 'publication', activityType: 'Newspaper Article', recommendedPoints: 15, maxPoints: 25, isActive: true, adminNote: 'National or state daily publication' },
  { id: 'pr-9', category: 'publication', activityType: 'Magazine Article', recommendedPoints: 12, maxPoints: 20, isActive: true, adminNote: 'University or national magazine' },
  
  // Paper Presentations
  { id: 'pr-10', category: 'paper_presentation', activityType: 'International Conference', recommendedPoints: 35, maxPoints: 50, isActive: true, adminNote: 'Keynote or paper delivery at international venue' },
  { id: 'pr-11', category: 'paper_presentation', activityType: 'National Conference', recommendedPoints: 25, maxPoints: 40, isActive: true, adminNote: 'National symposium paper presentation' },
  { id: 'pr-12', category: 'paper_presentation', activityType: 'Regional / State Seminar', recommendedPoints: 15, maxPoints: 25, isActive: true, adminNote: 'State level research colloquium' },
  
  // Seminars
  { id: 'pr-13', category: 'seminar', activityType: 'Resource Person / Speaker', recommendedPoints: 30, maxPoints: 45, isActive: true, adminNote: 'Invited speech or lecture' },
  { id: 'pr-14', category: 'seminar', activityType: 'Active Delegate', recommendedPoints: 12, maxPoints: 20, isActive: true, adminNote: 'Interactive participation' },
  { id: 'pr-15', category: 'seminar', activityType: 'Workshop Participant', recommendedPoints: 10, maxPoints: 15, isActive: true, adminNote: 'Skill acquisition workshop' },

  // College Programs
  { id: 'pr-16', category: 'college_program', activityType: 'Debate', recommendedPoints: 15, maxPoints: 30, isActive: true, adminNote: 'Inter-departmental debate' },
  { id: 'pr-17', category: 'college_program', activityType: 'Quiz', recommendedPoints: 12, maxPoints: 25, isActive: true, adminNote: 'Academic or general knowledge quiz' },
  { id: 'pr-18', category: 'college_program', activityType: 'Cultural Program', recommendedPoints: 15, maxPoints: 25, isActive: true, adminNote: 'Stage or musical performance' },
  { id: 'pr-19', category: 'college_program', activityType: 'Sports Fest', recommendedPoints: 15, maxPoints: 30, isActive: true, adminNote: 'Athletics, football, cricket, badminton' },
  
  // Outside College Programs
  { id: 'pr-20', category: 'outside_program', activityType: 'University Youth Festival', recommendedPoints: 30, maxPoints: 50, isActive: true, adminNote: 'Apex inter-varsity youth festival' },
  { id: 'pr-21', category: 'outside_program', activityType: 'Inter College Competition', recommendedPoints: 20, maxPoints: 35, isActive: true, adminNote: 'Host college invitational event' },
  { id: 'pr-22', category: 'outside_program', activityType: 'State Level Competition', recommendedPoints: 25, maxPoints: 40, isActive: true, adminNote: 'State ministry or council event' },

  // Competitions
  { id: 'pr-23', category: 'competition', activityType: 'Hackathon / Coding Sprint', recommendedPoints: 30, maxPoints: 50, isActive: true, adminNote: 'Software engineering or technical hackathon' },
  { id: 'pr-24', category: 'competition', activityType: 'Speech / Oratory', recommendedPoints: 15, maxPoints: 30, isActive: true, adminNote: 'Extempore or prepared speech' },
  
  // Awards & Other
  { id: 'pr-25', category: 'award', activityType: 'Government / National Honor', recommendedPoints: 50, maxPoints: 100, isActive: true, adminNote: 'State/National youth council honor' },
  { id: 'pr-26', category: 'award', activityType: 'Institutional Excellence Award', recommendedPoints: 30, maxPoints: 50, isActive: true, adminNote: 'College annual day top honour' },
  { id: 'pr-27', category: 'other_activity', activityType: 'Social Outreach / NSS / NCC', recommendedPoints: 15, maxPoints: 30, isActive: true, adminNote: 'Community service or leadership camp' },
];

export const INITIAL_RANK_RULES: RankPointRule[] = [
  { id: 'rr-1', rankName: '1st', points: 20, isActive: true, description: 'First place gold award' },
  { id: 'rr-2', rankName: '2nd', points: 15, isActive: true, description: 'Second place silver award' },
  { id: 'rr-3', rankName: '3rd', points: 10, isActive: true, description: 'Third place bronze award' },
  { id: 'rr-4', rankName: 'Winner', points: 25, isActive: true, description: 'Champion / Title Holder' },
  { id: 'rr-5', rankName: 'Runner Up', points: 18, isActive: true, description: 'Tournament runner up' },
  { id: 'rr-6', rankName: 'Finalist', points: 8, isActive: true, description: 'Qualified for grand finals' },
  { id: 'rr-7', rankName: 'Semi Finalist', points: 5, isActive: true, description: 'Top 4 finalist' },
  { id: 'rr-8', rankName: 'Special Mention', points: 8, isActive: true, description: 'Jury commendation award' },
  { id: 'rr-9', rankName: 'Participation', points: 3, isActive: true, description: 'Verified delegate participation' },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'std-1',
    admissionNumber: 'ADM2026-001',
    name: 'Rahbar Islam',
    email: 'rahbar.islam@imperial.edu',
    phone: '+91 98765 43201',
    address: 'Kishanganj, Bihar',
    course: 'B.Tech Computer Science & AI',
    department: 'No-Department',
    batch: '2023-2026',
    avatarUrl: 'https://image.pollinations.ai/prompt/portrait-of-a-smart-young-indian-muslim-boy-student-wearing-kufi-cap-smiling-photorealistic?width=500&height=500&nologo=true&seed=1', // AI Generated Muslim Boy,
    isActive: true,
    totalPoints: 155,
    approvedCount: 9,
    pendingCount: 1,
    rank: 1,
    bio: 'Honor student, research author, and collegiate literary coordinator from Kishanganj, Bihar. Active contributor in academic writing and youth leadership.',
    createdAt: '2025-08-10T10:00:00Z',
  },
  {
    id: 'std-2',
    admissionNumber: 'ADM2026-002',
    name: 'Ajmal',
    email: 'ajmal@imperial.edu',
    phone: '+91 98765 43202',
    address: 'Patna, Bihar',
    course: 'B.Sc. Biotechnology',
    department: 'No-Department',
    batch: '2023-2026',
    avatarUrl: 'https://image.pollinations.ai/prompt/portrait-of-a-confident-young-south-asian-muslim-boy-student-wearing-kufi-cap-photorealistic?width=500&height=500&nologo=true&seed=2', // AI Generated Muslim Boy,
    isActive: true,
    totalPoints: 138,
    approvedCount: 8,
    pendingCount: 0,
    rank: 2,
    bio: 'Young researcher in bioremediation and biotechnology with multiple presentations in national symposiums.',
    createdAt: '2025-08-10T10:15:00Z',
  },
  {
    id: 'std-3',
    admissionNumber: 'ADM2026-003',
    name: 'Muzammil',
    email: 'muzammil@imperial.edu',
    phone: '+91 98765 43203',
    address: 'Purnea, Bihar',
    course: 'B.Tech Information Technology',
    department: 'No-Department',
    batch: '2024-2028',
    avatarUrl: 'https://image.pollinations.ai/prompt/portrait-of-a-friendly-young-indian-muslim-boy-student-wearing-kufi-cap-and-glasses-photorealistic?width=500&height=500&nologo=true&seed=3', // AI Generated Muslim Boy,
    isActive: true,
    totalPoints: 125,
    approvedCount: 7,
    pendingCount: 1,
    rank: 3,
    bio: 'Algorithmic coder, hackathon victor, and lead developer of campus mobility and education tools.',
    createdAt: '2025-08-12T11:00:00Z',
  },
  {
    id: 'std-4',
    admissionNumber: 'ADM2026-004',
    name: 'Gulam Sarwar',
    email: 'gulam.sarwar@imperial.edu',
    phone: '+91 98765 43204',
    address: 'Araria, Bihar',
    course: 'M.A. Urdu & Comparative Literature',
    department: 'No-Department',
    batch: '2024-2026',
    avatarUrl: 'https://image.pollinations.ai/prompt/portrait-of-a-young-indian-muslim-boy-student-wearing-traditional-cap-photorealistic?width=500&height=500&nologo=true&seed=4', // AI Generated Muslim Boy,
    isActive: true,
    totalPoints: 112,
    approvedCount: 6,
    pendingCount: 0,
    rank: 4,
    bio: 'Master of classical prosody, ghazal and essayist, university gold medalist in bilingual parliamentary debates.',
    createdAt: '2025-08-14T09:30:00Z',
  },
  {
    id: 'std-5',
    admissionNumber: 'ADM2026-005',
    name: 'Sanawar Raza',
    email: 'sanawar.raza@imperial.edu',
    phone: '+91 98765 43205',
    address: 'Katihar, Bihar',
    course: 'B.Com Honours',
    department: 'No-Department',
    batch: '2023-2026',
    avatarUrl: 'https://image.pollinations.ai/prompt/portrait-of-a-cheerful-young-south-asian-muslim-boy-student-wearing-kufi-cap-photorealistic?width=500&height=500&nologo=true&seed=5', // AI Generated Muslim Boy,
    isActive: true,
    totalPoints: 98,
    approvedCount: 5,
    pendingCount: 1,
    rank: 5,
    bio: 'State-level finance forum winner, entrepreneurship cell secretary, and youth economic analyst.',
    createdAt: '2025-08-15T14:20:00Z',
  },
  {
    id: 'std-6',
    admissionNumber: 'ADM2026-006',
    name: 'Asif Raza',
    email: 'asif.raza@imperial.edu',
    phone: '+91 98765 43206',
    address: 'Darbhanga, Bihar',
    course: 'B.Sc. Mathematics & Statistics',
    department: 'No-Department',
    batch: '2023-2026',
    avatarUrl: 'https://image.pollinations.ai/prompt/portrait-of-a-young-indian-muslim-boy-student-wearing-kufi-cap-outdoor-lighting-photorealistic?width=500&height=500&nologo=true&seed=6', // AI Generated Muslim Boy,
    isActive: true,
    totalPoints: 88,
    approvedCount: 5,
    pendingCount: 0,
    rank: 6,
    bio: 'Mathematical Olympiad scholar, cryptography researcher, and academic tutor in statistics.',
    createdAt: '2025-08-16T16:00:00Z',
  },
  {
    id: 'std-7',
    admissionNumber: 'ADM2026-007',
    name: 'Arsalan',
    email: 'arsalan@imperial.edu',
    phone: '+91 98765 43207',
    address: 'Gaya, Bihar',
    course: 'B.Tech Mechanical Engineering',
    department: 'No-Department',
    batch: '2023-2027',
    avatarUrl: 'https://image.pollinations.ai/prompt/portrait-of-a-studious-young-south-asian-muslim-boy-student-wearing-kufi-cap-photorealistic?width=500&height=500&nologo=true&seed=7', // AI Generated Muslim Boy,
    isActive: true,
    totalPoints: 76,
    approvedCount: 4,
    pendingCount: 1,
    rank: 7,
    bio: 'Autonomous robotics engineer with smart drone prototype showcased at national technical summit.',
    createdAt: '2025-08-18T10:00:00Z',
  },
  {
    id: 'std-8',
    admissionNumber: 'ADM2026-008',
    name: 'Hasan',
    email: 'hasan@imperial.edu',
    phone: '+91 98765 43208',
    address: 'Bhagalpur, Bihar',
    course: 'B.A. English Literature',
    department: 'No-Department',
    batch: '2024-2027',
    avatarUrl: 'https://image.pollinations.ai/prompt/portrait-of-a-young-indian-muslim-boy-student-wearing-kufi-cap-studio-lighting-photorealistic?width=500&height=500&nologo=true&seed=8', // AI Generated Muslim Boy,
    isActive: true,
    totalPoints: 64,
    approvedCount: 3,
    pendingCount: 0,
    rank: 8,
    bio: 'Campus journal editor-in-chief, youth policy debater, and short story writer.',
    createdAt: '2025-08-20T11:45:00Z',
  },
  {
    id: 'std-9',
    admissionNumber: 'ADM2026-009',
    name: 'Adil Raza',
    email: 'adil.raza@imperial.edu',
    phone: '+91 98765 43209',
    address: 'Muzaffarpur, Bihar',
    course: 'B.Sc. Physics',
    department: 'No-Department',
    batch: '2024-2027',
    avatarUrl: 'https://image.pollinations.ai/prompt/portrait-of-a-handsome-young-south-asian-muslim-boy-student-wearing-kufi-cap-photorealistic?width=500&height=500&nologo=true&seed=9', // AI Generated Muslim Boy,
    isActive: true,
    totalPoints: 54,
    approvedCount: 3,
    pendingCount: 1,
    rank: 9,
    bio: 'Astrophysics enthusiast, state science exhibition merit awardee, and laboratory fellow.',
    createdAt: '2025-08-22T08:30:00Z',
  },
  {
    id: 'std-10',
    admissionNumber: 'ADM2026-010',
    name: 'Asad Raza',
    email: 'asad.raza@imperial.edu',
    phone: '+91 98765 43210',
    address: 'Kishanganj, Bihar',
    course: 'B.A. Journalism & Mass Comm',
    department: 'No-Department',
    batch: '2024-2027',
    avatarUrl: 'https://image.pollinations.ai/prompt/portrait-of-a-young-indian-muslim-boy-student-wearing-kufi-cap-bright-smile-photorealistic?width=500&height=500&nologo=true&seed=10', // AI Generated Muslim Boy,
    isActive: true,
    totalPoints: 45,
    approvedCount: 2,
    pendingCount: 0,
    rank: 10,
    bio: 'Documentary creator focusing on educational accessibility and grassroots student engagement in Kishanganj.',
    createdAt: '2025-08-25T13:10:00Z',
  },
];

export const INITIAL_SUBMISSIONS: ActivitySubmission[] = [
  // 1. Publications
  {
    id: 'sub-pub-1',
    studentId: 'std-1',
    studentName: 'Rahbar Islam',
    studentAdmissionNo: 'ADM2026-001',
    studentCourse: 'B.A. English Literature',
    studentDepartment: 'No-Department',
    category: 'publication',
    subType: 'Article',
    title: 'Echoes of the Renaissance in Contemporary Post-Colonial Fiction',
    venueOrOrganizer: 'The National Literary Review Daily',
    date: '2026-02-14',
    description: 'A comprehensive 2,500-word critical evaluation examining intertextuality and humanistic philosophy in post-colonial prose.',
    externalLink: 'https://literaryreview.example.org/echoes-renaissance-fiction',
    imageUrl: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 15,
    awardedPoints: 15,
    status: 'approved',
    adminReviewNote: 'Excellent analytical critique. Fully verified against physical print edition.',
    reviewedBy: 'Dr. Katherine Vance (Dean)',
    reviewedAt: '2026-02-16T11:00:00Z',
    isFeatured: true,
    featuredOrder: 1,
    featuredTitle: 'Featured Critique of the Month',
    featuredDescription: 'Masterful prose review featured on national literary syndicates.',
    createdAt: '2026-02-15T09:00:00Z',
    updatedAt: '2026-02-16T11:00:00Z',
  },
  {
    id: 'sub-pub-2',
    studentId: 'std-5',
    studentName: 'Sanawar Raza',
    studentAdmissionNo: 'ADM2026-005',
    studentCourse: 'M.A. Urdu & Comparative Literature',
    studentDepartment: 'No-Department',
    category: 'publication',
    subType: 'Ghazal',
    title: 'Safar-e-Tamanna (The Journey of Longing)',
    venueOrOrganizer: 'Adabi Dunya Quarterly Journal',
    date: '2026-01-28',
    description: 'Original 7-couplet classical ghazal rendered in Bahr-e-Ramal exploring metaphysical perseverance.',
    externalLink: 'https://adabidunya.example.org/tariq-ghazal-2026',
    imageUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 20,
    awardedPoints: 20,
    status: 'approved',
    adminReviewNote: 'Flawless poetic meter and remarkable artistic depth.',
    reviewedBy: 'Prof. S. Ahmed',
    reviewedAt: '2026-02-01T15:30:00Z',
    isFeatured: true,
    featuredOrder: 2,
    featuredTitle: 'Classical Ghazal Composition',
    featuredDescription: 'Award-winning poetic verses published in premier literary journal.',
    createdAt: '2026-01-29T10:00:00Z',
    updatedAt: '2026-02-01T15:30:00Z',
  },
  {
    id: 'sub-pub-3',
    studentId: 'std-5',
    studentName: 'Sanawar Raza',
    studentAdmissionNo: 'ADM2026-005',
    studentCourse: 'M.A. Urdu & Comparative Literature',
    studentDepartment: 'No-Department',
    category: 'publication',
    subType: 'Naat',
    title: 'Noor-e-Madina: Devotional Anthology Verse',
    venueOrOrganizer: 'Al-Huda Islamic Herald',
    date: '2026-01-10',
    description: 'Devotional tribute composed in traditional reverent rhyme scheme, commended by literary critics.',
    imageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 20,
    awardedPoints: 25,
    status: 'approved',
    adminReviewNote: 'Awarded bonus 5 points for distinguished regional broadcast selection.',
    reviewedBy: 'Admin Board',
    reviewedAt: '2026-01-12T10:00:00Z',
    isFeatured: true,
    featuredOrder: 3,
    createdAt: '2026-01-10T14:00:00Z',
    updatedAt: '2026-01-12T10:00:00Z',
  },
  {
    id: 'sub-pub-4',
    studentId: 'std-2',
    studentName: 'Ajmal',
    studentAdmissionNo: 'ADM2026-002',
    studentCourse: 'B.Sc. Biotechnology',
    studentDepartment: 'No-Department',
    category: 'publication',
    subType: 'Research Article',
    title: 'Microbial Degradation of Polyethylene Terephthalate in Coastal Waters',
    venueOrOrganizer: 'International Journal of Environmental Biotechnology (Scopus Indexed)',
    date: '2026-02-05',
    description: 'Original research paper detailing bacterial enzymatic degradation pathways observed in saline isolates.',
    externalLink: 'https://doi.org/10.1016/j.envbio.2026.02.019',
    imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 35,
    awardedPoints: 40,
    status: 'approved',
    adminReviewNote: 'High impact index factor journal. Outstanding achievement for an undergraduate.',
    reviewedBy: 'Dr. Marcus Webb',
    reviewedAt: '2026-02-08T09:00:00Z',
    isFeatured: true,
    featuredOrder: 4,
    featuredTitle: 'High-Impact Scopus Research Publication',
    featuredDescription: 'Breakthrough environmental biodegradation study in peer-reviewed journal.',
    createdAt: '2026-02-06T10:00:00Z',
    updatedAt: '2026-02-08T09:00:00Z',
  },
  {
    id: 'sub-pub-5',
    studentId: 'std-1',
    studentName: 'Rahbar Islam',
    studentAdmissionNo: 'ADM2026-001',
    studentCourse: 'B.A. English Literature',
    studentDepartment: 'No-Department',
    category: 'publication',
    subType: 'Essay',
    title: 'The Architecture of Silence in Modernist Poetry',
    venueOrOrganizer: 'Chronicle of Higher Arts',
    date: '2025-11-20',
    description: 'Exploration of deliberate omissions, caesuras, and typographic voids in mid-20th-century poetry.',
    externalLink: 'https://chroniclearts.example.org/silence-modernist',
    imageUrl: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 12,
    awardedPoints: 15,
    status: 'approved',
    reviewedBy: 'Editorial Committee',
    reviewedAt: '2025-11-23T11:00:00Z',
    isFeatured: false,
    createdAt: '2025-11-21T08:00:00Z',
    updatedAt: '2025-11-23T11:00:00Z',
  },
  {
    id: 'sub-pub-6',
    studentId: 'std-15',
    studentName: 'Rahbar Islam',
    studentAdmissionNo: 'ADM2026-001',
    studentCourse: 'B.A. English Literature',
    studentDepartment: 'No-Department',
    category: 'publication',
    subType: 'Poem',
    title: 'Whispers from the Gulmohar Branch',
    venueOrOrganizer: 'State Youth Poetry Anthology 2025',
    date: '2025-12-18',
    description: 'Lyrical free-verse piece selected among the top 10 youth verses in the state anthology.',
    imageUrl: 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 12,
    awardedPoints: 15,
    status: 'approved',
    reviewedBy: 'Prof. Alok Gupta',
    reviewedAt: '2025-12-20T10:00:00Z',
    isFeatured: false,
    createdAt: '2025-12-19T09:00:00Z',
    updatedAt: '2025-12-20T10:00:00Z',
  },
  {
    id: 'sub-pub-7',
    studentId: 'std-4',
    studentName: 'Gulam Sarwar',
    studentAdmissionNo: 'ADM2026-004',
    studentCourse: 'B.Com Honours',
    studentDepartment: 'No-Department',
    category: 'publication',
    subType: 'Newspaper Article',
    title: 'Decentralized Finance and Micro-Lending in Rural Agrarian Hubs',
    venueOrOrganizer: 'The Economic Express Daily',
    date: '2026-01-15',
    description: 'Op-ed analyzing financial technology adoption in Tier-3 rural agricultural cooperatives.',
    externalLink: 'https://economicexpress.example.com/defi-rural-microfinance',
    imageUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 15,
    awardedPoints: 18,
    status: 'approved',
    reviewedBy: 'Dr. Vance',
    reviewedAt: '2026-01-18T10:00:00Z',
    isFeatured: true,
    featuredOrder: 5,
    createdAt: '2026-01-16T14:00:00Z',
    updatedAt: '2026-01-18T10:00:00Z',
  },
  {
    id: 'sub-pub-8',
    studentId: 'std-1',
    studentName: 'Rahbar Islam',
    studentAdmissionNo: 'ADM2026-001',
    studentCourse: 'B.A. English Literature',
    studentDepartment: 'No-Department',
    category: 'publication',
    subType: 'Story',
    title: 'The Clocktower of Alipore: A Historical Novelette',
    venueOrOrganizer: 'Heritage Lore Gazette',
    date: '2026-02-28',
    description: 'Suspenseful historical narrative woven around the 19th-century colonial telegraph office.',
    imageUrl: 'https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 15,
    awardedPoints: 15,
    status: 'approved',
    reviewedBy: 'Literature Board',
    reviewedAt: '2026-03-02T16:00:00Z',
    isFeatured: false,
    createdAt: '2026-03-01T12:00:00Z',
    updatedAt: '2026-03-02T16:00:00Z',
  },
  {
    id: 'sub-pub-9',
    studentId: 'std-3',
    studentName: 'Muzammil',
    studentAdmissionNo: 'ADM2026-003',
    studentCourse: 'B.Tech Computer Science',
    studentDepartment: 'No-Department',
    category: 'publication',
    subType: 'Magazine Article',
    title: 'Demystifying Zero-Knowledge Proofs for Modern Web Applications',
    venueOrOrganizer: 'TechBytes University Quarterly',
    date: '2026-02-20',
    description: 'Introductory deep dive explaining zk-SNARKs and confidential consensus algorithms with diagrams.',
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 12,
    awardedPoints: 15,
    status: 'approved',
    reviewedBy: 'Tech Editorial',
    reviewedAt: '2026-02-22T10:00:00Z',
    isFeatured: false,
    createdAt: '2026-02-21T09:00:00Z',
    updatedAt: '2026-02-22T10:00:00Z',
  },
  {
    id: 'sub-pub-10',
    studentId: 'std-8',
    studentName: 'Hasan',
    studentAdmissionNo: 'ADM2026-008',
    studentCourse: 'B.A. Political Science',
    studentDepartment: 'No-Department',
    category: 'publication',
    subType: 'Article',
    title: 'Civic Engagement Indices Among Gen-Z Voters in Urban Centers',
    venueOrOrganizer: 'Public Sphere Review',
    date: '2026-03-04',
    description: 'Field survey analysis detailing youth voter turnout dynamics and digital grassroots organizing.',
    status: 'pending',
    recommendedPoints: 15,
    awardedPoints: 0,
    isFeatured: false,
    createdAt: '2026-03-04T10:00:00Z',
    updatedAt: '2026-03-04T10:00:00Z',
  },

  // 2. Paper Presentations
  {
    id: 'sub-pres-1',
    studentId: 'std-2',
    studentName: 'Ajmal',
    studentAdmissionNo: 'ADM2026-002',
    studentCourse: 'B.Sc. Biotechnology',
    studentDepartment: 'No-Department',
    category: 'paper_presentation',
    subType: 'International Conference',
    title: 'Enzymatic Biocatalysis for Microplastic Degradation in Closed Aquatic Habitats',
    venueOrOrganizer: 'World Bio-Engineering Congress, Singapore',
    date: '2026-01-20',
    description: 'Delivered 25-minute oral technical presentation before international panels; received best presentation commendation.',
    externalLink: 'https://wbec2026.org/proceedings/fatima-abstract',
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&auto=format&fit=crop&q=80',
    participationRank: 'Winner',
    recommendedPoints: 35,
    awardedPoints: 45,
    status: 'approved',
    adminReviewNote: 'Premier global conference with distinction. Verified by institutional sponsorship board.',
    reviewedBy: 'Prof. Helen Clark',
    reviewedAt: '2026-01-25T11:00:00Z',
    isFeatured: true,
    featuredOrder: 1,
    featuredTitle: 'World Bio-Engineering Oral Presentation',
    featuredDescription: 'Award-winning international paper presentation in Singapore.',
    createdAt: '2026-01-22T08:00:00Z',
    updatedAt: '2026-01-25T11:00:00Z',
  },
  {
    id: 'sub-pres-2',
    studentId: 'std-3',
    studentName: 'Muzammil',
    studentAdmissionNo: 'ADM2026-003',
    studentCourse: 'B.Tech Computer Science',
    studentDepartment: 'No-Department',
    category: 'paper_presentation',
    subType: 'National Conference',
    title: 'Adaptive Graph Neural Networks for Real-Time Campus Transit Optimization',
    venueOrOrganizer: 'National Symposium on Artificial Intelligence & Smart Cities (IIT Delhi)',
    date: '2026-02-12',
    description: 'Presented novel dynamic scheduling heuristic reducing student bus waiting latencies by 32%.',
    imageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&auto=format&fit=crop&q=80',
    participationRank: '2nd',
    recommendedPoints: 25,
    awardedPoints: 35,
    status: 'approved',
    adminReviewNote: 'Verified certificate and paper accepted in conference IEEE proceedings.',
    reviewedBy: 'Dr. A. Sen',
    reviewedAt: '2026-02-15T14:00:00Z',
    isFeatured: true,
    featuredOrder: 2,
    createdAt: '2026-02-13T10:00:00Z',
    updatedAt: '2026-02-15T14:00:00Z',
  },
  {
    id: 'sub-pres-3',
    studentId: 'std-6',
    studentName: 'Asif Raza',
    studentAdmissionNo: 'ADM2026-006',
    studentCourse: 'B.Sc. Physics',
    studentDepartment: 'No-Department',
    category: 'paper_presentation',
    subType: 'National Conference',
    title: 'Spectroscopic Signatures of High-Redshift Gamma-Ray Bursts',
    venueOrOrganizer: 'All-India Astronomical Society Colloquium',
    date: '2025-12-05',
    description: 'Technical paper presentation detailing analysis from satellite sky telescope datasets.',
    imageUrl: 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?w=800&auto=format&fit=crop&q=80',
    participationRank: '1st',
    recommendedPoints: 25,
    awardedPoints: 35,
    status: 'approved',
    reviewedBy: 'Dept Head Physics',
    reviewedAt: '2025-12-08T10:00:00Z',
    isFeatured: true,
    featuredOrder: 3,
    createdAt: '2025-12-06T09:00:00Z',
    updatedAt: '2025-12-08T10:00:00Z',
  },
  {
    id: 'sub-pres-4',
    studentId: 'std-7',
    studentName: 'Arsalan',
    studentAdmissionNo: 'ADM2026-007',
    studentCourse: 'B.Tech Mechanical Engineering',
    studentDepartment: 'No-Department',
    category: 'paper_presentation',
    subType: 'Regional / State Seminar',
    title: 'Aerodynamic Optimization of Lightweight VTOL Drones for Rural Medical Delivery',
    venueOrOrganizer: 'State Council of Science & Technology Annual Conclave',
    date: '2026-01-18',
    description: 'Demonstrated 3D printed airfoil prototypes with wind tunnel validation data.',
    imageUrl: 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&auto=format&fit=crop&q=80',
    participationRank: '1st',
    recommendedPoints: 20,
    awardedPoints: 28,
    status: 'approved',
    reviewedBy: 'Dean Engineering',
    reviewedAt: '2026-01-21T11:00:00Z',
    isFeatured: false,
    createdAt: '2026-01-19T10:00:00Z',
    updatedAt: '2026-01-21T11:00:00Z',
  },

  // 3. Seminars
  {
    id: 'sub-sem-1',
    studentId: 'std-4',
    studentName: 'Gulam Sarwar',
    studentAdmissionNo: 'ADM2026-004',
    studentCourse: 'B.Com Honours',
    studentDepartment: 'No-Department',
    category: 'seminar',
    subType: 'Resource Person / Speaker',
    title: 'Youth Leadership & Ethical Venture Capital in Emerging Markets',
    venueOrOrganizer: 'National Youth Entrepreneurship Forum, Mumbai',
    date: '2026-02-18',
    description: 'Invited student panellist addressing 300+ delegates on early-stage seed funding ethics.',
    imageUrl: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 30,
    awardedPoints: 30,
    status: 'approved',
    adminReviewNote: 'Distinguished speaking invitation confirmed with invitation letter.',
    reviewedBy: 'Admin Office',
    reviewedAt: '2026-02-21T12:00:00Z',
    isFeatured: true,
    featuredOrder: 1,
    createdAt: '2026-02-19T10:00:00Z',
    updatedAt: '2026-02-21T12:00:00Z',
  },
  {
    id: 'sub-sem-2',
    studentId: 'std-10',
    studentName: 'Adil Raza',
    studentAdmissionNo: 'ADM2026-010',
    studentCourse: 'B.Sc. Chemistry',
    studentDepartment: 'No-Department',
    category: 'seminar',
    subType: 'Workshop Participant',
    title: 'Advanced Mass Spectrometry & Nuclear Magnetic Resonance Hands-on Training',
    venueOrOrganizer: 'Central Instrumentation Research Center',
    date: '2026-01-22',
    description: 'Three-day intensive technical workshop on spectral interpretation and HPLC instrumentation.',
    imageUrl: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 10,
    awardedPoints: 12,
    status: 'approved',
    reviewedBy: 'Dr. P. Roy',
    reviewedAt: '2026-01-26T10:00:00Z',
    isFeatured: false,
    createdAt: '2026-01-24T09:00:00Z',
    updatedAt: '2026-01-26T10:00:00Z',
  },

  // 4. College Programs
  {
    id: 'sub-col-1',
    studentId: 'std-1',
    studentName: 'Rahbar Islam',
    studentAdmissionNo: 'ADM2026-001',
    studentCourse: 'B.A. English Literature',
    studentDepartment: 'No-Department',
    category: 'college_program',
    subType: 'Debate',
    title: 'Annual Inter-Departmental Parliamentary Debate 2026',
    venueOrOrganizer: 'Auditorium Hall A, Imperial College',
    date: '2026-01-30',
    description: 'Captained the winning Humanities debaters on the motion: AI will liberate rather than suppress artistic agency.',
    participationRank: '1st',
    imageUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 15,
    awardedPoints: 25,
    status: 'approved',
    adminReviewNote: 'Champion title + Best Speaker distinction awarded.',
    reviewedBy: 'Student Affairs',
    reviewedAt: '2026-02-02T10:00:00Z',
    isFeatured: false,
    createdAt: '2026-01-31T11:00:00Z',
    updatedAt: '2026-02-02T10:00:00Z',
  },
  {
    id: 'sub-col-2',
    studentId: 'std-3',
    studentName: 'Muzammil',
    studentAdmissionNo: 'ADM2026-003',
    studentCourse: 'B.Tech Computer Science',
    studentDepartment: 'No-Department',
    category: 'college_program',
    subType: 'Quiz',
    title: 'Imperial Grand Science & Tech Trivia Bowl',
    venueOrOrganizer: 'Main Senate Hall',
    date: '2026-02-08',
    description: 'Scored top marks across 5 rounds spanning quantum mechanics, Turing machines, and astrophysics.',
    participationRank: '1st',
    imageUrl: 'https://images.unsplash.com/photo-1517048676732-d65bc937f952?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 12,
    awardedPoints: 20,
    status: 'approved',
    reviewedBy: 'Quiz Committee',
    reviewedAt: '2026-02-10T10:00:00Z',
    isFeatured: false,
    createdAt: '2026-02-09T09:00:00Z',
    updatedAt: '2026-02-10T10:00:00Z',
  },

  // 5. Outside College Programs
  {
    id: 'sub-out-1',
    studentId: 'std-4',
    studentName: 'Gulam Sarwar',
    studentAdmissionNo: 'ADM2026-004',
    studentCourse: 'B.Com Honours',
    studentDepartment: 'No-Department',
    category: 'outside_program',
    subType: 'University Youth Festival',
    title: 'Apex Inter-University Youth Conclave Extempore Speech',
    venueOrOrganizer: 'State Central University, Capital City',
    date: '2026-02-03',
    description: 'Represented Imperial College against 42 competing collegiate teams in the English elocution tournament.',
    participationRank: 'Winner',
    imageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 30,
    awardedPoints: 35,
    status: 'approved',
    adminReviewNote: 'State level gold medal trophy brought to college.',
    reviewedBy: 'Principal Office',
    reviewedAt: '2026-02-05T12:00:00Z',
    isFeatured: true,
    featuredOrder: 1,
    featuredTitle: 'State Inter-Varsity Extempore Winner',
    featuredDescription: 'Clinched gold trophy at the 42-institution State Youth Conclave.',
    createdAt: '2026-02-04T10:00:00Z',
    updatedAt: '2026-02-05T12:00:00Z',
  },
  {
    id: 'sub-out-2',
    studentId: 'std-7',
    studentName: 'Arsalan',
    studentAdmissionNo: 'ADM2026-007',
    studentCourse: 'B.Tech Mechanical Engineering',
    studentDepartment: 'No-Department',
    category: 'outside_program',
    subType: 'Inter College Competition',
    title: 'Formula Green Electric Kart Grand Prix',
    venueOrOrganizer: 'Bhartiya Motorsports Academy, Coimbatore',
    date: '2026-01-14',
    description: 'Served as mechanical drivetrain lead; vehicle completed endurance test with zero mechanical faults.',
    participationRank: '2nd',
    imageUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 25,
    awardedPoints: 30,
    status: 'approved',
    reviewedBy: 'Sports & Technical Board',
    reviewedAt: '2026-01-17T11:00:00Z',
    isFeatured: false,
    createdAt: '2026-01-15T09:00:00Z',
    updatedAt: '2026-01-17T11:00:00Z',
  },

  // 6. Competitions
  {
    id: 'sub-comp-1',
    studentId: 'std-3',
    studentName: 'Muzammil',
    studentAdmissionNo: 'ADM2026-003',
    studentCourse: 'B.Tech Computer Science',
    studentDepartment: 'No-Department',
    category: 'competition',
    subType: 'Hackathon / Coding Sprint',
    title: 'CodeForge 36-Hour National Collegiate Hackathon',
    venueOrOrganizer: 'TechHub Innovation Arena, Bangalore',
    date: '2026-01-26',
    description: 'Built peer-to-peer decentralized disaster SOS beacon application using mesh networking and WebRTC.',
    participationRank: '1st',
    imageUrl: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 30,
    awardedPoints: 40,
    status: 'approved',
    adminReviewNote: 'First place out of 120 national teams. Grand cash prize & trophy.',
    reviewedBy: 'Prof. S. Rangan',
    reviewedAt: '2026-01-29T10:00:00Z',
    isFeatured: true,
    featuredOrder: 1,
    featuredTitle: 'CodeForge National Hackathon Champion',
    featuredDescription: 'Led 1st prize winning team building mesh emergency beacons.',
    createdAt: '2026-01-27T10:00:00Z',
    updatedAt: '2026-01-29T10:00:00Z',
  },
  {
    id: 'sub-comp-2',
    studentId: 'std-16',
    studentName: 'Asad Raza',
    studentAdmissionNo: 'ADM2026-010',
    studentCourse: 'B.Sc. Sports Science',
    studentDepartment: 'No-Department',
    category: 'competition',
    subType: 'Sports / Athletics',
    title: 'South Zone Inter-Collegiate Badminton Championships',
    venueOrOrganizer: 'State Sports Authority Stadium',
    date: '2026-02-10',
    description: 'Reached men singles finals without dropping a single set in preliminary rounds.',
    participationRank: 'Runner Up',
    imageUrl: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 20,
    awardedPoints: 25,
    status: 'approved',
    reviewedBy: 'Director of Physical Education',
    reviewedAt: '2026-02-12T10:00:00Z',
    isFeatured: false,
    createdAt: '2026-02-11T09:00:00Z',
    updatedAt: '2026-02-12T10:00:00Z',
  },

  // 7. Awards & Achievements
  {
    id: 'sub-awd-1',
    studentId: 'std-1',
    studentName: 'Rahbar Islam',
    studentAdmissionNo: 'ADM2026-001',
    studentCourse: 'B.A. English Literature',
    studentDepartment: 'No-Department',
    category: 'award',
    subType: 'Institutional Excellence Award',
    title: 'Chancellor Gold Medal for Literary & Outreach Eminence 2025',
    venueOrOrganizer: 'Annual Convocation & Awards Day, Imperial College',
    date: '2025-12-22',
    description: 'Highest collegiate honor conferred for outstanding lifetime student contribution to literary publications and campus outreach.',
    imageUrl: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80',
    participationRank: 'Winner',
    recommendedPoints: 40,
    awardedPoints: 50,
    status: 'approved',
    adminReviewNote: 'Institutional apex medal recorded.',
    reviewedBy: 'Chancellor Panel',
    reviewedAt: '2025-12-22T17:00:00Z',
    isFeatured: true,
    featuredOrder: 1,
    featuredTitle: 'Chancellor Gold Medal for Literary Eminence',
    featuredDescription: 'Awarded highest institutional honour for literary and campus impact.',
    createdAt: '2025-12-22T12:00:00Z',
    updatedAt: '2025-12-22T17:00:00Z',
  },
  {
    id: 'sub-awd-2',
    studentId: 'std-2',
    studentName: 'Ajmal',
    studentAdmissionNo: 'ADM2026-002',
    studentCourse: 'B.Sc. Biotechnology',
    studentDepartment: 'No-Department',
    category: 'award',
    subType: 'Government / National Honor',
    title: 'National Young Bio-Innovator Fellowship 2026',
    venueOrOrganizer: 'Department of Science & Technology, Govt. of India',
    date: '2026-02-01',
    description: 'Competitive fellowship grant awarded to top 50 undergraduate scientists nationwide for marine enzyme research.',
    imageUrl: 'https://images.unsplash.com/photo-1567427017947-545c5f8d16ad?w=800&auto=format&fit=crop&q=80',
    participationRank: 'Winner',
    recommendedPoints: 50,
    awardedPoints: 50,
    status: 'approved',
    adminReviewNote: 'Prestigious national fellowship verified with gazette notification.',
    reviewedBy: 'Dean of Research',
    reviewedAt: '2026-02-03T10:00:00Z',
    isFeatured: true,
    featuredOrder: 2,
    featuredTitle: 'National Young Bio-Innovator Fellowship',
    featuredDescription: 'Prestigious government scientific fellowship for marine enzymatic research.',
    createdAt: '2026-02-02T10:00:00Z',
    updatedAt: '2026-02-03T10:00:00Z',
  },

  // 8. Other Activities
  {
    id: 'sub-oth-1',
    studentId: 'std-8',
    studentName: 'Hasan',
    studentAdmissionNo: 'ADM2026-008',
    studentCourse: 'B.A. Political Science',
    studentDepartment: 'No-Department',
    category: 'other_activity',
    subType: 'Social Outreach / NSS / NCC',
    title: 'Rural Digital Literacy & Voting Rights Outreach Drive',
    venueOrOrganizer: 'NSS Special Camp, Rampur Village',
    date: '2026-01-12',
    description: 'Organized 7-day rural educational mission imparting smartphone digital payments and civic voter registration to 450+ villagers.',
    imageUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 15,
    awardedPoints: 20,
    status: 'approved',
    adminReviewNote: 'Exemplary community outreach service record.',
    reviewedBy: 'NSS Officer',
    reviewedAt: '2026-01-15T11:00:00Z',
    isFeatured: false,
    createdAt: '2026-01-13T09:00:00Z',
    updatedAt: '2026-01-15T11:00:00Z',
  },
  {
    id: 'sub-oth-2',
    studentId: 'std-1',
    studentName: 'Rahbar Islam',
    studentAdmissionNo: 'ADM2026-001',
    studentCourse: 'B.A. English Literature',
    studentDepartment: 'No-Department',
    category: 'other_activity',
    subType: 'Campus Leadership',
    title: 'Chief Editor: Annual College Souvenir & Outreach Chronicle 2026',
    venueOrOrganizer: 'Imperial Editorial Board',
    date: '2026-02-25',
    description: 'Directed editorial curation, proofing, and layout for 240-page institutional anthology.',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80',
    recommendedPoints: 15,
    awardedPoints: 20,
    status: 'approved',
    reviewedBy: 'Publications Committee',
    reviewedAt: '2026-02-27T10:00:00Z',
    isFeatured: false,
    createdAt: '2026-02-26T08:00:00Z',
    updatedAt: '2026-02-27T10:00:00Z',
  },
];

export const INITIAL_FEATURED_TITLES: FeaturedStudentTitle[] = [
  {
    id: 'ft-1',
    title: 'Best Writer & Literary Achiever',
    studentId: 'std-1',
    studentName: 'Rahbar Islam',
    studentAdmissionNo: 'ADM2026-001',
    studentDepartment: 'No-Department',
    studentCourse: 'B.Tech Computer Science & AI',
    studentAvatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&auto=format&fit=crop&q=80',
    shortDescription: 'Scholar from Kishanganj, Bihar. Author of 10+ recognized publications, national review articles, and collegiate parliamentary debate victor.',
    sessionYear: '2025-2026',
    positionSubtitle: 'Gold Medalist & Literary Secretary',
    displayOrder: 1,
    isFeatured: true,
    isActive: true,
    showOnHomePage: true,
    createdAt: '2026-01-15T10:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
  },
  {
    id: 'ft-2',
    title: 'Best Paper Presenter & Researcher',
    studentId: 'std-2',
    studentName: 'Ajmal',
    studentAdmissionNo: 'ADM2026-002',
    studentDepartment: 'No-Department',
    studentCourse: 'B.Sc. Biotechnology',
    studentAvatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=500&auto=format&fit=crop&q=80',
    shortDescription: 'Recipient of National Bio-Innovator Fellowship with award-winning presentation at Singapore Bio-Engineering Congress.',
    sessionYear: '2025-2026',
    positionSubtitle: 'National Science Fellow',
    displayOrder: 2,
    isFeatured: true,
    isActive: true,
    showOnHomePage: true,
    createdAt: '2026-01-16T10:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
  },
  {
    id: 'ft-3',
    title: 'Best Innovator & Tech Champion',
    studentId: 'std-3',
    studentName: 'Muzammil',
    studentAdmissionNo: 'ADM2026-003',
    studentDepartment: 'No-Department',
    studentCourse: 'B.Tech Information Technology',
    studentAvatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=500&auto=format&fit=crop&q=80',
    shortDescription: '1st place winner at CodeForge National Hackathon and author of machine learning transportation optimization papers.',
    sessionYear: '2025-2026',
    positionSubtitle: 'Lead Systems Architect',
    displayOrder: 3,
    isFeatured: true,
    isActive: true,
    showOnHomePage: true,
    createdAt: '2026-01-18T10:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
  },
  {
    id: 'ft-4',
    title: 'Best Orator & Debate Leader',
    studentId: 'std-4',
    studentName: 'Gulam Sarwar',
    studentAdmissionNo: 'ADM2026-004',
    studentDepartment: 'No-Department',
    studentCourse: 'M.A. Urdu & Comparative Literature',
    studentAvatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=500&auto=format&fit=crop&q=80',
    shortDescription: 'Winner of State Inter-University Youth Conclave and invited speaker at National Youth Entrepreneurship Forum.',
    sessionYear: '2025-2026',
    positionSubtitle: 'Apex Youth Conclave Winner',
    displayOrder: 4,
    isFeatured: true,
    isActive: true,
    showOnHomePage: true,
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
  },
  {
    id: 'ft-5',
    title: 'Best Ghazal & Classical Performer',
    studentId: 'std-5',
    studentName: 'Sanawar Raza',
    studentAdmissionNo: 'ADM2026-005',
    studentDepartment: 'No-Department',
    studentCourse: 'B.Com Honours',
    studentAvatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=500&auto=format&fit=crop&q=80',
    shortDescription: 'Distinguished student entrepreneur published in economic forums and composer of acclaimed classical naat anthologies.',
    sessionYear: '2025-2026',
    positionSubtitle: 'Master of Classical Verse',
    displayOrder: 5,
    isFeatured: true,
    isActive: true,
    showOnHomePage: true,
    createdAt: '2026-01-22T10:00:00Z',
    updatedAt: '2026-02-20T10:00:00Z',
  },
];

export const INITIAL_BADGES: AchievementBadge[] = [
  {
    id: 'bdg-1',
    name: 'Publication Star',
    icon: 'BookOpen',
    description: 'Published 3 or more approved literary, research, or journal publications.',
    minPointsOrCriteria: '3+ Publications',
    assignedStudentIds: ['std-1', 'std-2', 'std-5'],
    isActive: true,
    color: '#3b82f6',
  },
  {
    id: 'bdg-2',
    name: 'Presentation Expert',
    icon: 'Presentation',
    description: 'Delivered technical paper presentations at national or international conferences.',
    minPointsOrCriteria: 'National/Intl Presentation',
    assignedStudentIds: ['std-2', 'std-3', 'std-6', 'std-7'],
    isActive: true,
    color: '#8b5cf6',
  },
  {
    id: 'bdg-3',
    name: 'Competition Champion',
    icon: 'Trophy',
    description: 'Earned 1st place or Winner rank in inter-college or national competitions.',
    minPointsOrCriteria: '1st Place Rank',
    assignedStudentIds: ['std-1', 'std-3', 'std-4', 'std-6'],
    isActive: true,
    color: '#f59e0b',
  },
  {
    id: 'bdg-4',
    name: 'Top Performer',
    icon: 'Crown',
    description: 'Accumulated over 100 verified achievement points in the institutional outreach database.',
    minPointsOrCriteria: '100+ Total Points',
    assignedStudentIds: ['std-1', 'std-2', 'std-3'],
    isActive: true,
    color: '#eab308',
  },
  {
    id: 'bdg-5',
    name: 'Literary Star',
    icon: 'Feather',
    description: 'Demonstrated mastery in creative writing, poetry, ghazal, or collegiate debates.',
    minPointsOrCriteria: 'Literary Eminence',
    assignedStudentIds: ['std-1', 'std-4', 'std-5', 'std-15'],
    isActive: true,
    color: '#10b981',
  },
  {
    id: 'bdg-6',
    name: 'Outstanding Student',
    icon: 'Award',
    description: 'Recognized for exemplary all-around discipline, academic outreach, and social leadership.',
    minPointsOrCriteria: 'Dean Honor Roll',
    assignedStudentIds: ['std-1', 'std-2', 'std-3', 'std-4', 'std-8'],
    isActive: true,
    color: '#ec4899',
  },
];

export const INITIAL_POINT_HISTORY: PointHistoryRecord[] = [
  {
    id: 'ph-1',
    studentId: 'std-1',
    studentName: 'Rahbar Islam',
    activityId: 'sub-pub-1',
    activityTitle: 'Echoes of the Renaissance in Contemporary Post-Colonial Fiction',
    category: 'publication',
    previousPoints: 0,
    pointsAdded: 15,
    finalPoints: 15,
    adminName: 'Dr. Katherine Vance',
    date: '2026-02-16T11:00:00Z',
    reason: 'Approved peer-reviewed article in National Literary Review',
  },
  {
    id: 'ph-2',
    studentId: 'std-1',
    studentName: 'Rahbar Islam',
    activityId: 'sub-col-1',
    activityTitle: 'Annual Inter-Departmental Parliamentary Debate 2026',
    category: 'college_program',
    previousPoints: 15,
    pointsAdded: 25,
    finalPoints: 40,
    adminName: 'Student Affairs',
    date: '2026-02-02T10:00:00Z',
    reason: '1st rank winner + Best Speaker points awarded',
  },
  {
    id: 'ph-3',
    studentId: 'std-1',
    studentName: 'Rahbar Islam',
    activityId: 'sub-awd-1',
    activityTitle: 'Chancellor Gold Medal for Literary & Outreach Eminence 2025',
    category: 'award',
    previousPoints: 40,
    pointsAdded: 50,
    finalPoints: 90,
    adminName: 'Chancellor Panel',
    date: '2025-12-22T17:00:00Z',
    reason: 'Chancellor Gold Medal Awarded',
  },
  {
    id: 'ph-4',
    studentId: 'std-2',
    studentName: 'Ajmal',
    activityId: 'sub-pub-4',
    activityTitle: 'Microbial Degradation of Polyethylene Terephthalate in Coastal Waters',
    category: 'publication',
    previousPoints: 0,
    pointsAdded: 40,
    finalPoints: 40,
    adminName: 'Dr. Marcus Webb',
    date: '2026-02-08T09:00:00Z',
    reason: 'Approved Scopus publication in Environmental Biotechnology',
  },
  {
    id: 'ph-5',
    studentId: 'std-2',
    studentName: 'Ajmal',
    activityId: 'sub-pres-1',
    activityTitle: 'Enzymatic Biocatalysis for Microplastic Degradation in Closed Aquatic Habitats',
    category: 'paper_presentation',
    previousPoints: 40,
    pointsAdded: 45,
    finalPoints: 85,
    adminName: 'Prof. Helen Clark',
    date: '2026-01-25T11:00:00Z',
    reason: 'International oral presentation winner in Singapore',
  },
  {
    id: 'ph-6',
    studentId: 'std-3',
    studentName: 'Muzammil',
    activityId: 'sub-comp-1',
    activityTitle: 'CodeForge 36-Hour National Collegiate Hackathon',
    category: 'competition',
    previousPoints: 0,
    pointsAdded: 40,
    finalPoints: 40,
    adminName: 'Prof. S. Rangan',
    date: '2026-01-29T10:00:00Z',
    reason: 'National Hackathon Champion (1st Prize)',
  },
];

export const INITIAL_CERTIFICATES: IssuedCertificate[] = [
  {
    id: 'SOMS-CERT-2026-9812',
    studentId: 'std-1',
    studentName: 'Rahbar Islam',
    studentAdmissionNo: 'ADM2026-001',
    activityId: 'sub-awd-1',
    activityTitle: 'Chancellor Gold Medal for Literary & Outreach Eminence',
    category: 'award',
    achievementDetails: 'Conferred for unparalleled literary mastery, research publications, and university outreach service.',
    issueDate: '2026-01-10',
    organizationName: 'Darul Huda Islamic University',
    pointsAwarded: 50,
    verificationHash: 'v-9812-rahbar-chancellor-medal',
  },
  {
    id: 'SOMS-CERT-2026-5541',
    studentId: 'std-2',
    studentName: 'Ajmal',
    studentAdmissionNo: 'ADM2026-002',
    activityId: 'sub-pres-1',
    activityTitle: 'World Bio-Engineering Congress Oral Paper Delivery',
    category: 'paper_presentation',
    achievementDetails: 'Oral technical keynote at Singapore international symposium.',
    issueDate: '2026-01-28',
    organizationName: 'Darul Huda Islamic University',
    pointsAwarded: 45,
    verificationHash: 'v-5541-ajmal-singapore-bio',
  },
  {
    id: 'SOMS-CERT-2026-7730',
    studentId: 'std-3',
    studentName: 'Muzammil',
    studentAdmissionNo: 'ADM2026-003',
    activityId: 'sub-comp-1',
    activityTitle: 'CodeForge 36-Hour National Collegiate Hackathon Winner',
    category: 'competition',
    achievementDetails: 'First place out of 120 participating collegiate institutions.',
    issueDate: '2026-02-02',
    organizationName: 'Darul Huda Islamic University',
    pointsAwarded: 40,
    verificationHash: 'v-7730-muzammil-codeforge-champ',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-1',
    action: 'SYSTEM_INITIALIZATION',
    adminName: 'System Kernel',
    details: 'Initialized institutional outreach database with academic schema, point rules, and sample records.',
    timestamp: '2026-02-01T08:00:00Z',
  },
  {
    id: 'log-2',
    action: 'APPROVE_SUBMISSION',
    adminName: 'admin',
    details: 'Approved article "Echoes of the Renaissance" submitted by Rahbar Islam (ADM2026-001) and awarded 15 points.',
    timestamp: '2026-02-16T11:00:00Z',
    recordType: 'publication',
    recordId: 'sub-pub-1',
  },
  {
    id: 'log-3',
    action: 'FEATURE_STUDENT_TITLE',
    adminName: 'admin',
    details: 'Assigned and featured title "Best Writer & Literary Achiever" to Rahbar Islam.',
    timestamp: '2026-02-17T09:30:00Z',
    recordType: 'featuredStudentTitle',
    recordId: 'ft-1',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    recipientRole: 'admin',
    title: 'New Student Submission Received',
    message: 'Hasan submitted an article "Civic Engagement Indices" for review.',
    type: 'info',
    relatedActivityId: 'sub-pub-10',
    isRead: false,
    createdAt: '2026-03-04T10:05:00Z',
  },
  {
    id: 'notif-2',
    recipientRole: 'student',
    studentId: 'std-1',
    title: 'Submission Approved & Points Awarded',
    message: 'Your article "Echoes of the Renaissance" has been approved! +15 Points added.',
    type: 'success',
    relatedActivityId: 'sub-pub-1',
    isRead: false,
    createdAt: '2026-02-16T11:05:00Z',
  },
  {
    id: 'notif-3',
    recipientRole: 'student',
    studentId: 'std-1',
    title: 'Honour Conferred: Featured Student',
    message: 'Congratulations! You have been featured on the college website as "Best Writer & Literary Achiever".',
    type: 'success',
    isRead: false,
    createdAt: '2026-02-17T09:35:00Z',
  },
];
